### ISSUE TITLE
Trying to access array offset on null when submitting composer form with empty attributes

### ISSUE THREAD

**Issue by ghost** [Mesuva/msv_multiple_file_selector_attribute#1]
Hey there

I am using your package in my concretecms project. When trying to publish a new page, I get 
```
Trying to access array offset on null

/var/www/html/packages/msv_multiple_file_selector_attribute/attributes/multiple_file_selector/controller.php(79):  Whoops\Exception\ErrorException->null
/var/www/html/packages/msv_multiple_file_selector_attribute/attributes/multiple_file_selector/controller.php(79):  Whoops\Run->handleError
/var/www/html/concrete/src/Page/Type/Composer/Control/CollectionAttributeControl.php(171):   Concrete\Package\MsvMultipleFileSelectorAttribute\Attribute\MultipleFileSelector\Controller->createAttributeValueFromRequest
```

As you can see this error comes from [line 79](https://github.com/Mesuva/msv_multiple_file_selector_attribute/blob/bc3afc4545286078d2e947f199f925818a7f30ea/attributes/multiple_file_selector/controller.php#L79) in `Concrete\Package\MsvMultipleFileSelectorAttribute\Attribute\MultipleFileSelector\Controller` because as `$data`can be null.

I suggest the following change:
```
if (isset($data['value']) && is_array($data['value'])) {
    $list = implode(',', $data['value']);
}
```

For context, I'm using concretecms version 9.3.2, php 8.3.7 and Multiple File Selector Attribute - 0.9.

Thank you!

**Comment by Mesuva** [comment]
Thank you for this, I've pushed up a fix as per your suggestion
